// export default {
//   defaultSidebar: [
//     {
//       type: "autogenerated",
//       dirName: ".",
//     },

//   ],
// };

// export default {
//   defaultSidebar: [
//     {
//       type: "category", // This creates a folder-like category in the sidebar
//       label: "🚀 Getting Started",
//       items: [
//         {
//           type: "autogenerated",
//           dirName: "intro", // This will pick up all files in the docs/intro folder
//         },
//       ],
//     },
//   ],
// };

export default {
  defaultSidebar: [
    {
      type: "category", // This creates a folder-like category in the sidebar
      label: "🚀 Getting Started",
      items: [
        {
          type: "autogenerated",
          dirName: "intro", // This will pick up all files in the docs/intro folder
        },
      ],
    },
    {
      type: "category", // New folder category
      label: "🔧 Setapp-deployment",
      items: [
        {
          type: "autogenerated",
          dirName: "Setappdeployment", // This will pick up all files in the docs/installation folder
        },
      ],
    },
    // {
    //   type: "category", // Another new folder category
    //   label: "📚 Documentation",
    //   items: [
    //     {
    //       type: "autogenerated",
    //       dirName: "documentation", // This will pick up all files in the docs/documentation folder
    //     },
    //   ],
    // },
    // {
    //   type: "category", // Another folder for guides
    //   label: "📖 Guides",
    //   items: [
    //     {
    //       type: "autogenerated",
    //       dirName: "guides", // This will pick up all files in the docs/guides folder
    //     },
    //   ],
    // },
  ],
};
